base: ""

training:
  epochs: 10
  batch_size: 32
  log_freq: 500 #Number of batches
  loss: "mse" #['huber', 'l1', 'mse']
  momentum: 0.9
  lr: 0.01
  lr_decay: 0.8
  lr_decay_step: 1000 #Decay the learning rate at every N batches (put "epoch" to use epochs as steps)

augmentation:
  RandomHorizontalFlip:
    - p: 0.5

XAI:
  enabled: True
  type: "sidu"

evaluation:
  classwise_metrics: True
  metrics:
  - "rmse"
  - "mae"
  - "mse"
  eval_freq: 5000

model:
  arch: "cspdarknet53"
  in_channels: 1
  weights: null
  finale_activation: null
  intermediate_outputs: null

data:
  classes:
  - "human"
  - "bicycle"
  - "motorcycle"
  - "vehicle"
  mask: Null #Mask losses for the clases below (set 'mask: Null' to disable ignoring)
  binary_cls: False
  root: "/Data/Harborfront_raw/"
  train: "data/Train_data.csv"
  valid:  "data/Valid_data.csv"
  test:  "data/Test_data.csv"
  
wandb:
  enabled: True
  plotting: True
  resume: null
  project_name: "Trace and Erase"
  entity: "repai"
  notes: ""
  tags:
    - Testing

unlearning:
  method: null
