base: ""

training:
  epochs: 10
  lr: 0.01
  batch_size: 8
  log_freq: 500 #Number of batches
  loss: "mse"

augmentation:
  RandomHorizontalFlip:
    - p: 0.5

XAI:
 type: "sidu"

evaluation:
  classwise_metrics: True
  metrics:
  - "rmse"
  - "mae"
  eval_freq: 5000

model:
  arch: "resnet50d"
  in_channels: 3
  weights: null
  finale_activation: null
  intermediate_outputs: 
    - "model.layer4[2].act3"

data:
  classes:
  - "human"
  - "bicycle"
  - "motorcycle"
  - "vehicle"
  binary_cls: False
  classwise: False
  root: "/Data/Harborfront_raw/"
  train: "data/Train_data.csv"
  valid: "data/Valid_data.csv"
  test: "data/Test_data.csv"
  

wandb:
  enabled: False
  plotting: True
  resume: null
  project_name: "Trace and Erase"
  entity: "user"
  notes: ""
  tags:
    - Baseline

unlearning:
  method: null