base: ""

training:
  epochs: 10
  batch_size: 8
  log_freq: 500 #Number of batches
  loss: "mse"
  lr: 0.01
  momentum: 0.9

augmentation:
  RandomHorizontalFlip:
    - p: 0.5

XAI:
 type: "sidu"

evaluation:
  classwise_metrics: True
  metrics:
  - "rmse"
  - "mae"
  eval_freq: 5000

model:
  arch: "resnet50d"
  in_channels: 3
  weights: null
  finale_activation: null
  intermediate_outputs: #print(model) to find layer names
    - "model.layer1[2].act3"
    - "model.layer2[2].act3" 
    - "model.layer3[2].act2"
    - "model.layer4[2].act3"

data:
  classes:
  - "human"
  - "bicycle"
  - "motorcycle"
  - "vehicle"
  binary_cls: True
  root: "/Data/Harborfront_raw/"
  train: "data/Test_data_reduced.csv" #"data/Train_data.csv"
  valid: "data/Valid_data.csv"
  test: "data/Test_data_reduced.csv" #"data/Test_data.csv"
  
wandb:
  enabled: True
  plotting: True
  resume: null
  project_name: "Trace and Erase"
  entity: "repai"
  notes: ""
  tags:
    - Baseline

unlearning:
  method: null