base: ""

training:
  epochs: 10
  lr: 0.01
  batch_size: 50
  log_freq: 500 #Number of batches
  loss: "mse"

augmentation:
  horizontal_flip:
    - p: 0.5

XAI:
 type: "sidu"

evaluation:
  classwise_metrics: True
  metrics:
  - "rmse"
  - "mae"
  eval_freq: 5000

model:
  arch: "resnet50d"
  weights: null

data:
  classes:
  - "human"
  - "bicycle"
  - "motorcycle"
  - "vehicle"
  root: "data/example_data/"
  train: "data/example_data/annotations.csv"
  valid: "data/example_data/annotations.csv"
  test: "data/example_data/annotations.csv"

wandb:
  enabled: False
  plotting: True
  resume: null
  project_name: "Trace and Erase"
  entity: "user"
  notes: ""
  tags:
    - Baseline

unlearning:
  method: null